# Generated by Django 4.1.4 on 2022-12-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EnergyHH",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "settleDate",
                    models.DateField(auto_now=True, verbose_name="Settlement Date"),
                ),
                ("settlePeriod", models.IntegerField(verbose_name="Settlement Period")),
                ("CCGT", models.IntegerField(verbose_name="Combined Gas Production")),
                ("oil", models.IntegerField(verbose_name="Oil Production")),
                ("coal", models.IntegerField(verbose_name="Coal Production")),
                ("nuclear", models.IntegerField(verbose_name="Nuclear Production")),
                ("wind", models.IntegerField(verbose_name="Wind Production")),
                (
                    "pumped_storage",
                    models.IntegerField(verbose_name="Pumped Storage Production"),
                ),
                ("hydro", models.IntegerField(verbose_name="Hydro Production")),
                ("OCGT", models.IntegerField(verbose_name="Open Cycle Gas Production")),
                ("other", models.IntegerField(verbose_name="Other Production")),
                (
                    "france_IFA",
                    models.IntegerField(verbose_name="France IFA Interconnector"),
                ),
                (
                    "northern_ireland",
                    models.IntegerField(verbose_name="Northern Ireland Interconnector"),
                ),
                (
                    "netherlands",
                    models.IntegerField(verbose_name="Netherlands Interconnector"),
                ),
                ("ireland", models.IntegerField(verbose_name="Ireland Interconnector")),
                ("biomass", models.IntegerField(verbose_name="Biomass Production")),
                ("belgium", models.IntegerField(verbose_name="Belgium Interconnector")),
                (
                    "france_eleclink",
                    models.IntegerField(verbose_name="France Eleclink Interconnector"),
                ),
                (
                    "france_IFA2",
                    models.IntegerField(verbose_name="France IFA2 Interconnector"),
                ),
                ("norway", models.IntegerField(verbose_name="Norway Interconnector")),
            ],
        ),
    ]
