# Generated by Django 4.1.5 on 2023-01-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UKSummary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyhh',
            name='settleDate',
            field=models.DateField(verbose_name='Settlement Date'),
        ),
    ]
